apiVersion: v2
appVersion: 23.1.1
dependencies:
- name: alfresco-common
  repository: https://alfresco.github.io/alfresco-helm-charts
  version: 2.1.0
description: Alfresco Share Helm chart for Kubernetes
name: alfresco-share
type: application
version: 0.2.1
