apiVersion: v2
appVersion: 3.0.1
dependencies:
- name: alfresco-common
  repository: https://alfresco.github.io/alfresco-helm-charts/
  version: 2.1.0
- condition: activemq.enabled
  name: activemq
  repository: https://cbautistadev.github.io/alfresco-helm-charts/
  version: 3.4.1
description: A Helm chart for deploying Alfresco ai transformer service
name: alfresco-ai-transformer
type: application
version: 0.4.1
