apiVersion: v2
appVersion: 2.0.0
dependencies:
- name: alfresco-common
  repository: https://alfresco.github.io/alfresco-helm-charts/
  version: 2.1.0
description: A Helm chart for deploying Alfresco connector msteams service
name: alfresco-connector-msteams
type: application
version: 0.2.0
