apiVersion: v2
appVersion: 4.0.1
dependencies:
- name: alfresco-common
  repository: https://alfresco.github.io/alfresco-helm-charts/
  version: 2.1.0
- condition: activemq.enabled
  name: activemq
  repository: https://cbautistadev.github.io/alfresco-helm-charts/ 
  version: 3.4.1
- alias: ai
  condition: ai.enabled
  name: alfresco-ai-transformer
  repository: https://alfresco.github.io/alfresco-helm-charts/
  version: 0.2.0
description: A Helm chart for deploying Alfresco Transform Services
name: alfresco-transform-service
type: application
version: 0.3.2
