apiVersion: v2
name: alfresco-transform-service
description: A Helm chart for deploying Alfresco Transform Services
type: application
version: 0.3.2
appVersion: 4.0.1
dependencies:
  - name: alfresco-common
    version: 2.1.0
    repository: https://alfresco.github.io/alfresco-helm-charts/

