apiVersion: v2
appVersion: 5.18.3
dependencies:
- name: alfresco-common
  repository: https://alfresco.github.io/alfresco-helm-charts/
  version: 3.0.0
description: A CUSTOM Helm chart providing a basic Apache ActiveMQ deployment required to
  evaluate ACS (not meant to be used in production).
icon: https://avatars0.githubusercontent.com/u/391127?s=200&v=4
keywords:
- activemq
- message broker
name: activemq
sources:
- https://github.com/Alfresco/alfresco-helm-charts
version: 3.4.1
