apiVersion: v2
appVersion: 4.0.1
dependencies:
- name: alfresco-common
  repository: https://alfresco.github.io/alfresco-helm-charts/
  version: 2.1.0
- condition: activemq.enabled
  name: activemq
  repository: https://cbautistadev.github.io/alfresco-helm-charts/
  version: 3.3.0
- condition: postgresql.enabled
  name: postgresql
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 12.5.6
description: Alfresco Sync Service
icon: https://avatars0.githubusercontent.com/u/391127?s=200&v=4
keywords:
- syncservice
- alfresco
- application
name: alfresco-sync-service
sources:
- https://github.com/Alfresco/acs-deployment
version: 4.5.1
