apiVersion: v2
appVersion: 23.1.1
dependencies:
- name: alfresco-common
  repository: https://alfresco.github.io/alfresco-helm-charts/
  version: 3.0.0
- condition: postgresql.enabled
  name: postgresql
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 12.8.5
- alias: alfresco-control-center
  condition: alfresco-admin-app.enabled
  name: common
  repository: https://activiti.github.io/activiti-cloud-helm-charts
  version: 8.0.0
- alias: alfresco-digital-workspace
  condition: alfresco-digital-workspace.enabled
  name: common
  repository: https://activiti.github.io/activiti-cloud-helm-charts
  version: 8.0.0
- name: alfresco-repository
  repository: https://alfresco.github.io/alfresco-helm-charts/
  version: 0.1.1
- condition: activemq.enabled
  name: activemq
  repository: https://cbautistadev.github.io/alfresco-helm-charts/
  version: 3.4.1
- condition: alfresco-transform-service.enabled
  name: alfresco-transform-service
  repository: https://cbautistadev.github.io/alfresco-helm-charts/ 
  version: 0.3.2
- alias: alfresco-search
  condition: alfresco-search.enabled
  name: alfresco-search-service
  repository: https://alfresco.github.io/alfresco-helm-charts/
  version: 2.0.0
- condition: alfresco-sync-service.enabled
  name: alfresco-sync-service
  repository: https://alfresco.github.io/alfresco-helm-charts/
  version: 4.5.1
- condition: alfresco-search-enterprise.enabled
  name: alfresco-search-enterprise
  repository: https://alfresco.github.io/alfresco-helm-charts/
  version: 3.0.2
- condition: alfresco-connector-msteams.enabled
  name: alfresco-connector-msteams
  repository: https://cbautistadev.github.io/alfresco-helm-charts/
  version: 0.2.0
- alias: share
  condition: share.enabled
  name: alfresco-share
  repository: https://alfresco.github.io/alfresco-helm-charts/
  version: 0.2.1
- condition: alfresco-connector-ms365.enabled
  name: alfresco-connector-ms365
  repository: https://cbautistadev.github.io/alfresco-helm-charts/
  version: 0.4.0
- condition: alfresco-ai-transformer.enabled
  name: alfresco-ai-transformer
  repository: https://cbautistadev.github.io/alfresco-helm-charts/
  version: 0.4.1
- condition: elasticsearch.enabled
  name: elasticsearch
  repository: https://helm.elastic.co
  version: 7.17.3
description: A Helm chart for deploying Alfresco Content Services
home: https://www.alfresco.com
icon: https://avatars0.githubusercontent.com/u/391127?s=200&v=4
keywords:
- content
- content services
- alfresco
- alfresco content services
name: alfresco-content-services
sources:
- https://github.com/Alfresco/acs-deployment
version: 7.0.1
