#name of the workflow 
name: Release Charts

on:
  push:
  workflow_dispatch:
    

jobs:
  release:
    # depending on default permission settings for your org (contents being read-only or read-write for workloads), you will have to add permissions
    # see: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: check tags
        run: | 
          git fetch --tags >/dev/null 2>&1

          if ! git describe --tags --abbrev=0 HEAD~ 2>/dev/null; then
            git rev-list --max-parents=0 --first-parent HEAD
          fi     
   
 #     - name: custom packaging for subcharts 
  ##        rm -rf .cr-release-packages
    #       mkdir -p .cr-release-packages
     #      helm package ./charts/subcharts/activemq --destination=.cr-release-packages

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          charts_dir: ./charts/subchart
          skip_existing: true
          mark_as_latest: true
          skip_packaging: false
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"