name: Create and deploy charts
on: [push, workflow_dispatch, pull_request ]
jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - name: My first step - check out repository
        uses: actions/checkout@v4
      - name: Detect changed directories
        run: |
         # List changed files and extract unique directories
         CHANGED_DIRS=$(git diff --name-only HEAD^ HEAD | xargs -L1 dirname | uniq)
         echo "Changed directories: $CHANGED_DIRS" 
     
